version: '3.6'
services:
  mailhog:
    image: mailhog/mailhog
    environment:
      SMTP_HOST: mailhog
      SMTP_PORT: 1025
      SMTP_PASS: password
      SMTP_USER: user
      SMTP_SECURE: 'false'
      SMTP_SENDER: noreply@nextjs-starter-template.com
    ports:
      - 1025:1025 # smtp server
      - 8025:8025 # web ui
